server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com # eureka 服务端的实例名称
    #prefer-ip-address: true
  client:
    # false 表示不向注册中心注册自己
    register-with-eureka: false
    #false 表示自己端 就是注册中心，我的职责技术维护服务实例
    fetch-registry: false
    service-url:
      # 设置 与eureka server 交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://eureka7001.com:7001/eureka/
